## Lista 7 ##

### Zadanie 1. - podstawy sortowania ###

Zaimplementuj algorytm sortowania wektora liczb całkowitych względem kolejnych cyfr (od najbardziej znaczącej) tak, aby kolejne cyfry sortować raz malejąco, raz rosnąco (naprzemiennie). Dokładniej, posortuj tak, aby kolejne liczby o takim samej pierwszej cyfrze zostały dodatkowo posortowane względem drugiej cyfry, a liczby o takich samych: pierwszej i drugiej cyfrze zostały posortowane względem trzeciej cyfry, itd.

Zadanie wykonaj wielokrotnie korzystając z jednego (wybranego przez siebie) stabilnego algorytmu sortowania.

In [2]:
import numpy as np

In [190]:
VECTOR = list(np.random.randint(10, 1000, 100))
print(VECTOR)

[163, 111, 527, 619, 534, 698, 675, 560, 592, 642, 392, 364, 276, 129, 620, 84, 715, 899, 664, 485, 493, 849, 253, 564, 198, 788, 135, 116, 181, 794, 165, 200, 897, 585, 196, 110, 368, 913, 664, 754, 719, 911, 518, 362, 440, 204, 776, 698, 33, 922, 353, 687, 948, 686, 103, 515, 242, 528, 887, 512, 224, 84, 519, 250, 484, 485, 110, 34, 876, 546, 125, 233, 422, 505, 836, 75, 439, 713, 792, 445, 459, 992, 279, 21, 442, 84, 532, 578, 633, 81, 61, 864, 323, 602, 883, 238, 581, 609, 98, 473]


Wybrany algorytm sortujący - sortowanie szybkie - zaimplemntowany dwukrotnie dla sortowania rosnącego i sortowania malejącego.

In [191]:
def quick_sort_asc(arr, low, high):
        if low > high or low < 0:
            return
        
        p, arr =  partition_asc(arr, low, high)

        quick_sort_asc(arr, low, p - 1)
        quick_sort_asc(arr, p + 1, high)

        return arr


def partition_asc(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] <= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]
    
    i += 1
    arr[i], arr[high] = arr[high], arr[i]
    
    return i, arr

def quick_sort_desc(arr, low, high):
    if low > high: # or high >= len(arr):
        return
    
    p, arr =  partition(arr, low, high)

    quick_sort_desc(arr, low, p - 1)
    quick_sort_desc(arr, p + 1, high)

    return arr


def partition(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] >= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]
    
    i += 1
    arr[i], arr[high] = arr[high], arr[i]
    
    return i, arr

Sortowanie listy wedłu podanych w treści zadania zasad.

In [192]:
def sort_vector(vec):
    l = len(str(max(vec))) # sprawdzenie ile cyfr ma ajwiększa liczba z listy
    prefixes = list()
    # stworzenie listy prefixów
    for n in range(l, 1, -1):
        prefixes.append([i * 10 ** (n-1) for i in range(10 ** (l - n + 1)  + 1)])

    rev = 1
    vec = quick_sort_asc(vec, 0, len(vec) - 1)

    for pref in prefixes:

        for p in range(len(pref) - 1):

            temp = [v for v in vec if (v >= pref[p] and v < pref[p+1])]
            if len(temp):
                low = vec.index(temp[0])
                high = vec.index(temp[-1])
                if rev:
                    temp = quick_sort_desc(temp, 0, len(temp) - 1)                    
                else:
                    temp = quick_sort_asc(temp, 0, len(temp) - 1)


                #temp = sorted(temp, reverse=rev)
                vec[low:high + 1] = temp

        if rev:
            rev = 0
        else:
            rev = 1
    return vec
        


V_NEW = sort_vector(VECTOR)
print('\nPOSORTOWANA LISTA:')
print(V_NEW)


POSORTOWANA LISTA:
[98, 81, 84, 84, 84, 75, 61, 33, 34, 21, 196, 198, 181, 163, 165, 135, 125, 129, 110, 110, 111, 116, 110, 103, 276, 279, 250, 253, 242, 233, 238, 224, 200, 204, 392, 362, 364, 368, 353, 323, 493, 484, 485, 485, 473, 459, 440, 442, 445, 439, 422, 592, 581, 585, 578, 560, 564, 546, 532, 534, 527, 528, 512, 515, 518, 519, 505, 698, 698, 698, 698, 686, 687, 675, 664, 664, 664, 642, 633, 620, 619, 602, 609, 698, 792, 794, 788, 776, 754, 713, 715, 719, 897, 899, 883, 887, 876, 864, 849, 836, 992, 948, 922, 911, 913]


### Zadanie 2 - ograniczony zbiór wartości ###

Dany jest wektor robotów (z poprzedniej listy). Wykorzystaj algorytm sortowania przez zliczanie do sortowania względem rozdzielczości kamery.

In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(0, 10, 20)
print(A)

In [13]:
def counting_sort(l):
    j = [0] * (max(l) + 1)
    output = [0] * (len(l) + 1)

    for i in l:
        j[i] += 1
    
    for i in range(1, len(j)):
        j[i] += j[i - 1]
    
    for i in range(len(l)):
        a = l[i]
        b = j[a]
        output[b] = a
        j[a] -= 1

    return output

In [14]:
from L6_0_data_structure import create_m_bots

# wektor robotów
robots = create_m_bots(20)
robots = [b.save_robot() for b in robots]
robots

[{'id': '1101', 'typ': 'GUA', 'masa': 539, 'roz': 10},
 {'id': '1010', 'typ': 'WUC', 'masa': 1398, 'roz': 16},
 {'id': '1111', 'typ': 'GNW', 'masa': 151, 'roz': 29},
 {'id': '1110', 'typ': 'NNV', 'masa': 572, 'roz': 15},
 {'id': '0110', 'typ': 'GVW', 'masa': 81, 'roz': 27},
 {'id': '1101', 'typ': 'WNV', 'masa': 282, 'roz': 7},
 {'id': '0011', 'typ': 'GGV', 'masa': 827, 'roz': 6},
 {'id': '0001', 'typ': 'NUG', 'masa': 732, 'roz': 8},
 {'id': '1011', 'typ': 'GVG', 'masa': 1612, 'roz': 24},
 {'id': '1111', 'typ': 'UAA', 'masa': 1965, 'roz': 26},
 {'id': '0001', 'typ': 'VVN', 'masa': 1334, 'roz': 14},
 {'id': '0010', 'typ': 'AAG', 'masa': 1960, 'roz': 8},
 {'id': '0001', 'typ': 'NGV', 'masa': 1503, 'roz': 27},
 {'id': '0110', 'typ': 'WUN', 'masa': 1485, 'roz': 11},
 {'id': '0001', 'typ': 'NNV', 'masa': 62, 'roz': 23},
 {'id': '1000', 'typ': 'AUV', 'masa': 1815, 'roz': 19},
 {'id': '0100', 'typ': 'GWC', 'masa': 1733, 'roz': 11},
 {'id': '1111', 'typ': 'GAG', 'masa': 801, 'roz': 1},
 {'id': 

In [15]:
# wyodrębnienie rozdzielczości u umieszczenie warotści w liście 
L = [i['roz'] for i in robots]
# wywołanie sortowania przez zlicznie
resolutions = counting_sort(L)  
new_robots = []

# idąc po posortowanych rozdzielczościach ponowne scalenie listy robotów
for r in resolutions:
    for bot in robots:
        if bot['roz'] == r:
            new_robots.append(bot)
            robots.remove(bot)

for b in new_robots:
    print(b)

{'id': '1111', 'typ': 'GAG', 'masa': 801, 'roz': 1}
{'id': '1100', 'typ': 'CVA', 'masa': 1172, 'roz': 4}
{'id': '0011', 'typ': 'GGV', 'masa': 827, 'roz': 6}
{'id': '1101', 'typ': 'WNV', 'masa': 282, 'roz': 7}
{'id': '0001', 'typ': 'NUG', 'masa': 732, 'roz': 8}
{'id': '0010', 'typ': 'AAG', 'masa': 1960, 'roz': 8}
{'id': '1101', 'typ': 'GUA', 'masa': 539, 'roz': 10}
{'id': '0110', 'typ': 'WUN', 'masa': 1485, 'roz': 11}
{'id': '0100', 'typ': 'GWC', 'masa': 1733, 'roz': 11}
{'id': '1100', 'typ': 'CWA', 'masa': 1441, 'roz': 13}
{'id': '0001', 'typ': 'VVN', 'masa': 1334, 'roz': 14}
{'id': '1110', 'typ': 'NNV', 'masa': 572, 'roz': 15}
{'id': '1010', 'typ': 'WUC', 'masa': 1398, 'roz': 16}
{'id': '1000', 'typ': 'AUV', 'masa': 1815, 'roz': 19}
{'id': '0001', 'typ': 'NNV', 'masa': 62, 'roz': 23}
{'id': '1011', 'typ': 'GVG', 'masa': 1612, 'roz': 24}
{'id': '1111', 'typ': 'UAA', 'masa': 1965, 'roz': 26}
{'id': '0110', 'typ': 'GVW', 'masa': 81, 'roz': 27}
{'id': '0001', 'typ': 'NGV', 'masa': 1503, '

### Zadanie 3 - sortowanie ciągów ###
Dana jest dwuwymiarowa tablica liczb całkowitych. Zaimplementuj algorytm sortowania pozycyjnego w celu posortowania wierszy tablicy tak, aby kolejne kolumny tablicy określały kolejność wierszy w przypadku, gdy wartości w poprzednich kolumnach są jednakowe.

Sortowanie pozycyjne (radix sort) \
złożoność : O(n * m)

<b> Pseudokod </b>\
RadixSort(tab[],d)\
tab[] - 2-wymiarowa tablica nieposortowanych liczb\
d - długość tablicy
wykonuj\
   &nbsp;&nbsp; dla i:=d schodź do 1 wykonuj\
      &nbsp;&nbsp; &nbsp;&nbsp; posortuj stabilnie ciągi według i-tej pozycji;\
end;

In [30]:
L = np.random.randint(0, 7, (20, 3))
L

array([[5, 0, 4],
       [6, 1, 2],
       [5, 2, 3],
       [1, 5, 4],
       [5, 3, 6],
       [0, 1, 4],
       [2, 6, 1],
       [0, 0, 2],
       [5, 1, 6],
       [1, 5, 4],
       [3, 5, 1],
       [1, 0, 3],
       [0, 0, 2],
       [6, 6, 1],
       [6, 3, 5],
       [0, 1, 3],
       [1, 5, 1],
       [6, 2, 6],
       [1, 2, 6],
       [0, 5, 4]])

In [31]:
def radix_sort(t):
    n = len(t[0])
    for i in range(n - 1, -1, -1):
        t = sorted(t, key=lambda x: x[i])
    return t

radix_sort(L)
    

[array([0, 0, 2]),
 array([0, 0, 2]),
 array([0, 1, 3]),
 array([0, 1, 4]),
 array([0, 5, 4]),
 array([1, 0, 3]),
 array([1, 2, 6]),
 array([1, 5, 1]),
 array([1, 5, 4]),
 array([1, 5, 4]),
 array([2, 6, 1]),
 array([3, 5, 1]),
 array([5, 0, 4]),
 array([5, 1, 6]),
 array([5, 2, 3]),
 array([5, 3, 6]),
 array([6, 1, 2]),
 array([6, 2, 6]),
 array([6, 3, 5]),
 array([6, 6, 1])]

### Zadanie 4 - dziel i zwyciężaj ###

- Zaimplementuj algorytm szybkiego sortowania (quicksort) wektora robotów (z poprzedniej listy) względem zadanego parametru.

In [187]:
import random

# sortowanie szybkie z podziałem losowym pivot = random
def quick_sort_random(array):
    def quicksort(arr, start, stop):
        if(start < stop):
            pivotindex = partitionrand(arr,start, stop)
            quicksort(arr , start , pivotindex)
            quicksort(arr, pivotindex + 1, stop)


    def partitionrand(arr , start, stop):
        randpivot = random.randrange(start, stop)
        arr[start], arr[randpivot] = arr[randpivot], arr[start]
        return partition(arr, start, stop)
 

    def partition(arr,start,stop):
        pivot = start
        i = start - 1
        j = stop + 1
        while True:
            while True:
                i = i + 1
                if arr[i] >= arr[pivot]:
                    break
            while True:
                j = j - 1
                if arr[j] <= arr[pivot]:
                    break
            if i >= j:
                return j
            arr[i] , arr[j] = arr[j] , arr[i]
            
    quicksort(array, 0, len(array) - 1)
    
    return array


def quick_sort_random_desc(array):
    def quicksort(arr, start, stop):
        if(start < stop):
            pivotindex = partitionrand(arr,start, stop)
            quicksort(arr , start , pivotindex)
            quicksort(arr, pivotindex + 1, stop)


    def partitionrand(arr , start, stop):
        randpivot = random.randrange(start, stop)
        arr[start], arr[randpivot] = arr[randpivot], arr[start]
        return partition(arr, start, stop)
 

    def partition(arr,start,stop):
        pivot = start
        i = start - 1
        j = stop + 1
        while True:
            while True:
                i = i + 1
                if arr[i] <= arr[pivot]:
                    break
            while True:
                j = j - 1
                if arr[j] >= arr[pivot]:
                    break
            if i >= j:
                return j
            arr[i] , arr[j] = arr[j] , arr[i]
            
    quicksort(array, 0, len(array) - 1)
    
    return array

In [178]:
def sort_robots(bots, feat, kind=0):
        """
        :param list bots: wektor robotów
        :param feat: cecha według której sortujemy
        :param int kind: 0 -> rosnąco, 1 ->malejąco, 2 -> alfabetycznie
        :return list new_robots: lista robotów posortowana względem zadanego parametru
        """
        # wyciągniecie odpowiedniej cechy
        l = [b[feat] for b in bots]


        if kind == 0:
            l = quick_sort_random(l)
        elif kind == 1:
            l = quick_sort_random_desc(l)
        elif kind == 2: # alfabetycznie
            l = [str(n) for n in l]
            l = quick_sort_random_desc(l)
        
        
        new_robots = list()
        
        for r in l:
            for bot in bots:
                if bot[feat] == r:
                    new_robots.append(bot)
                    bots.remove(bot)

        return new_robots     


# Wywoałanie funkcji dla pierwszej części zadania
vector = create_m_bots(20)
vector = [b.save_robot() for b in vector]
feauture  = 'roz'
robots = sort_robots(vector, feat=feauture)
print(f"Wektor robotów posortowany względem parametru: {feauture}")
for r in robots:
    print(r)


Wektor robotów posortowany względem parametru: roz
{'id': '0101', 'typ': 'GCW', 'masa': 83, 'roz': 3}
{'id': '0101', 'typ': 'GGG', 'masa': 992, 'roz': 4}
{'id': '0101', 'typ': 'CNN', 'masa': 635, 'roz': 6}
{'id': '1011', 'typ': 'WWV', 'masa': 954, 'roz': 10}
{'id': '1111', 'typ': 'WGC', 'masa': 471, 'roz': 10}
{'id': '1101', 'typ': 'WNV', 'masa': 128, 'roz': 11}
{'id': '1101', 'typ': 'CAG', 'masa': 1808, 'roz': 11}
{'id': '0000', 'typ': 'WNW', 'masa': 1033, 'roz': 12}
{'id': '0111', 'typ': 'GCA', 'masa': 483, 'roz': 16}
{'id': '1001', 'typ': 'GVA', 'masa': 67, 'roz': 16}
{'id': '1010', 'typ': 'CVN', 'masa': 852, 'roz': 16}
{'id': '0110', 'typ': 'CUU', 'masa': 1967, 'roz': 17}
{'id': '1001', 'typ': 'CAG', 'masa': 756, 'roz': 18}
{'id': '1011', 'typ': 'CWC', 'masa': 862, 'roz': 19}
{'id': '1010', 'typ': 'GWG', 'masa': 1999, 'roz': 20}
{'id': '1100', 'typ': 'UWG', 'masa': 756, 'roz': 21}
{'id': '0001', 'typ': 'AVV', 'masa': 387, 'roz': 22}
{'id': '0011', 'typ': 'GWN', 'masa': 1707, 'roz':

- Rozwiń napisaną procedurę tak, aby przyjmowała listę parametrów robota (w zadanej kolejności, niekoniecznie wszystkie) wraz z kierunkiem sortowania (nierosnąco, niemalejąco, alfabetycznie, itd.). Sortowanie wykonaj po wszystkich zadanych parametrach (w zadanej kolejności i zadanym kierunku sortowania) tak, aby kolejne elementy listy o takim samym pierwszym parametrze zostały posortowanewzględem drugiego parametru, a o takim samym pierwszym i drugim parametrze – względem trzeciego parametru itd. Uwaga: Zwróć uwagę na stabilność procedury sortowania.

Do rozwiązania tego podpunktu wykorzystamy powyższą funkcję quicksort oraz sposób myślenia radix sort z zadania 3.

In [184]:
vector = create_m_bots(100)
vector = [b.save_robot() for b in vector]

In [195]:
features = {
        'id': 0,
        'roz': 1,
        'typ': 2,
    'masa': 1,
    }
feat_list = list(features.keys())
# odwrócenie listy cech
# feat_list.reverse()
feat_list

['id', 'roz', 'typ', 'masa']

In [196]:
for f in feat_list:
    vector = sort_robots(bots=vector, feat=f, kind=features[f])
    
vector

[{'id': '1000', 'typ': 'CVU', 'masa': 1971, 'roz': 13},
 {'id': '1110', 'typ': 'NNW', 'masa': 1951, 'roz': 11},
 {'id': '0100', 'typ': 'WWU', 'masa': 1931, 'roz': 11},
 {'id': '1001', 'typ': 'AAW', 'masa': 1917, 'roz': 28},
 {'id': '0011', 'typ': 'CCC', 'masa': 1910, 'roz': 18},
 {'id': '0100', 'typ': 'AGG', 'masa': 1902, 'roz': 20},
 {'id': '0111', 'typ': 'ANV', 'masa': 1851, 'roz': 10},
 {'id': '1011', 'typ': 'GWN', 'masa': 1849, 'roz': 19},
 {'id': '0001', 'typ': 'CAC', 'masa': 1849, 'roz': 22},
 {'id': '1111', 'typ': 'WGN', 'masa': 1841, 'roz': 24},
 {'id': '1011', 'typ': 'UNN', 'masa': 1821, 'roz': 8},
 {'id': '0111', 'typ': 'GAU', 'masa': 1807, 'roz': 8},
 {'id': '0101', 'typ': 'UWA', 'masa': 1800, 'roz': 5},
 {'id': '1010', 'typ': 'CCV', 'masa': 1790, 'roz': 2},
 {'id': '0010', 'typ': 'UVW', 'masa': 1786, 'roz': 29},
 {'id': '0110', 'typ': 'NCA', 'masa': 1776, 'roz': 29},
 {'id': '0110', 'typ': 'UNU', 'masa': 1760, 'roz': 7},
 {'id': '1011', 'typ': 'GVW', 'masa': 1751, 'roz': 7}

### Zadanie 5 - wizualizacja sortowania ###

- Zaimplementuj algorytm sortowania przez kopcowanie.

 - Proces sortowania przedstaw graficznie (np. korzystając z wykresu kolumnowego matplotlib). Wizualizacja ma wyświetlać kolejne kroki algorytmu, gdzie kolejny krok zachodzi po wykonaniu elementarnej operacji (porównywania liczb, zmiany położenia liczb w ciągu, itd.).
 - Wykonaj analogiczną wizualizację dla algorytmu sortowania szybkiego (quicksort). Obie wizualizacje przedstaw (wyświetl) równolegle.

In [188]:
import matplotlib.pyplot as plt
import multiprocessing as mp
import numpy as np


size = 20
INTERVAL = 0.5
L = np.random.randint(0, 100, size)
X = np.arange(size)

def heap_sort_global(l):
    def heapify(arr, n, i):
        largest = i # Ustawienie największego jako ojciec
        l = 2 * i + 1	 # lewy syn = 2*i + 1
        r = 2 * i + 2	 # prawy syn = 2*i + 2

        # Sprwdzamy czy lewy syn istnieje
        # i jest większy od ojca
        if l < n and arr[largest] < arr[l]:
            largest = l

        # Sprwdzamy czy prawy syn istnieje
        # i jest większy od ojca
        if r < n and arr[largest] < arr[r]:
            largest = r

        # Zmiana ojca jeśli spełniony jest warunek
        if largest != i:
            
            arr[i], arr[largest] = arr[largest], arr[i] # swap

            plt.bar(X, arr)
            plt.title('Sortowanie przez kopcowanie')
            plt.pause(INTERVAL)
            plt.clf()


            # ponowne wywołanie kopcowania
            heapify(arr, n, largest)


    def heapSort(arr):
        n = len(arr)

        # Budowanie największego kopca
        for i in range(n//2 - 1, -1, -1):
            heapify(arr, n, i)

        # ektrakcja elementów
        for i in range(n-1, 0, -1):

            arr[i], arr[0] = arr[0], arr[i] # zamiana

            plt.bar(X, arr)
            plt.title('Sortowanie przez kopcowanie')
            plt.pause(INTERVAL)
            plt.clf()

            heapify(arr, i, 0)

    heapSort(l)



def quic_sort_global(array):
    def quicksort(arr, start, stop):
        if(start < stop):
            pivotindex = partitionrand(arr,start, stop)
            quicksort(arr , start , pivotindex)
            quicksort(arr, pivotindex + 1, stop)


    def partitionrand(arr , start, stop):
        randpivot = random.randrange(start, stop)
        arr[start], arr[randpivot] = arr[randpivot], arr[start]
        plt.bar(X, arr)
        plt.title('Quicksort - sortowanie szybkie')
        plt.pause(INTERVAL)
        plt.clf()
        return partition(arr, start, stop)
 

    def partition(arr,start,stop):
        pivot = start
        i = start - 1
        j = stop + 1
        while True:
            while True:
                i = i + 1
                if arr[i] >= arr[pivot]:
                    break
            while True:
                j = j - 1
                if arr[j] <= arr[pivot]:
                    break
            if i >= j:
                return j
            arr[i] , arr[j] = arr[j] , arr[i]
            plt.bar(X, arr)
            plt.title('Quicksort - sortowanie szybkie')
            plt.pause(INTERVAL)
            plt.clf()
            
    quicksort(array, 0, len(array) - 1)
    
    return array

if __name__ == '__main__':
    
    task1 = mp.Process(target=heap_sort_global, args=(L,))
    task2 = mp.Process(target=quic_sort_global, args=(L,))

    task1.start()
    task2.start()

    plt.show()